enrollment No- 2021MSBDA032  , Assignment No -2

# Computing the Singular Value Decomposition (SVD) without using svd function 

In [43]:
import pandas as pd      # importing pandas,numpy and norm  for use purpose:
import numpy as np
from numpy.linalg import norm
my_data=pd.read_csv(r"C:\Users\DELL\Downloads\Untitled spreadsheet - Sheet1.csv") # importing my data from my file 

In [44]:
my_data     # This is my data and we are going to calculate svd here 

Serial.No  Age  Hours  Pages
0           1   22      9    110
1           2   32     12    121
2           3   21      7     80
3           4   22      8     88
4           5   32     10     90
5           6   44     11    102
6           7   22     12    109
7           8   56     10     98
8           9   72      9     81
9          10   10      6     53
10         11   22      7     61
11         12   23      8     77
12         13   44      5     43
13         14   34      8     79
14         15   37      9     86
15         16   68     10     91
16         17   25      4     34
17         18   26      3     22
18         19   21      6     48
19         20   21     10     97
20         21   19     11    119
21         22   19      8     66
22         23   18      7     56
23         24   33      9     99
24         25   31      5     49
25         26   30      9     82
26         27   53      9     93
27         28   44      8     72
28         29   42      9     81
29         30   28      7     68

In [45]:
my_data.shape # checking the dimension of my data :

(30, 4)

In [46]:
Array_matrix = my_data.to_numpy()   #converting my data into array form
Array_matrix

array([[  1,  22,   9, 110],
       [  2,  32,  12, 121],
       [  3,  21,   7,  80],
       [  4,  22,   8,  88],
       [  5,  32,  10,  90],
       [  6,  44,  11, 102],
       [  7,  22,  12, 109],
       [  8,  56,  10,  98],
       [  9,  72,   9,  81],
       [ 10,  10,   6,  53],
       [ 11,  22,   7,  61],
       [ 12,  23,   8,  77],
       [ 13,  44,   5,  43],
       [ 14,  34,   8,  79],
       [ 15,  37,   9,  86],
       [ 16,  68,  10,  91],
       [ 17,  25,   4,  34],
       [ 18,  26,   3,  22],
       [ 19,  21,   6,  48],
       [ 20,  21,  10,  97],
       [ 21,  19,  11, 119],
       [ 22,  19,   8,  66],
       [ 23,  18,   7,  56],
       [ 24,  33,   9,  99],
       [ 25,  31,   5,  49],
       [ 26,  30,   9,  82],
       [ 27,  53,   9,  93],
       [ 28,  44,   8,  72],
       [ 29,  42,   9,  81],
       [ 30,  28,   7,  68]], dtype=int64)

In [47]:
tp_matrix= Array_matrix.transpose()  # taking tranpose of the matrix which is created .
tp_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30],
       [ 22,  32,  21,  22,  32,  44,  22,  56,  72,  10,  22,  23,  44,
         34,  37,  68,  25,  26,  21,  21,  19,  19,  18,  33,  31,  30,
         53,  44,  42,  28],
       [  9,  12,   7,   8,  10,  11,  12,  10,   9,   6,   7,   8,   5,
          8,   9,  10,   4,   3,   6,  10,  11,   8,   7,   9,   5,   9,
          9,   8,   9,   7],
       [110, 121,  80,  88,  90, 102, 109,  98,  81,  53,  61,  77,  43,
         79,  86,  91,  34,  22,  48,  97, 119,  66,  56,  99,  49,  82,
         93,  72,  81,  68]], dtype=int64)

In [48]:
rd_matrix = np.dot(tp_matrix,Array_matrix) # Reducing the dimension of that matrix 
rd_matrix

array([[  9455,  15231,   3669,  34532],
       [ 15231,  37867,   8210,  78224],
       [  3669,   8210,   2160,  20818],
       [ 34532,  78224,  20818, 202611]], dtype=int64)

In [49]:
eig= np.linalg.eig(rd_matrix)  # need to find out the eigan values and the corosponding eigan vectors :
eig    

(array([2.42148961e+05, 7.10456556e+03, 2.82449002e+03, 1.49830186e+01]),
 array([[ 0.16074424,  0.32369266, -0.93206823,  0.02516277],
        [ 0.36505389,  0.85786183,  0.3613147 ,  0.01613767],
        [ 0.09407241, -0.01467674, -0.015744  , -0.99533266],
        [ 0.91216628, -0.39884927,  0.021275  ,  0.0917568 ]]))

In [50]:
eigan ,eig_vect = eig
print("The eigan values are ",eigan)
print("Corosponding Eigan vectors are",eig_vect)

The eigan values are  [2.42148961e+05 7.10456556e+03 2.82449002e+03 1.49830186e+01]
Corosponding Eigan vectors are [[ 0.16074424  0.32369266 -0.93206823  0.02516277]
 [ 0.36505389  0.85786183  0.3613147   0.01613767]
 [ 0.09407241 -0.01467674 -0.015744   -0.99533266]
 [ 0.91216628 -0.39884927  0.021275    0.0917568 ]]


In [51]:
mat_1=Array_matrix@eig_vect[:,0]/norm(Array_matrix@eig_vect[:,0]) # here we are going to compute SVD . This is the first step .
mat_2=Array_matrix@eig_vect[:,1]/norm(Array_matrix@eig_vect[:,1])
mat_1

array([0.22227171, 0.25098076, 0.1661907 , 0.18227975, 0.19411459,
       0.22577866, 0.2229515 , 0.22772831, 0.20822098, 0.11007668,
       0.13432607, 0.16524449, 0.11755165, 0.17776549, 0.19348456,
       0.22626808, 0.08788893, 0.06652221, 0.11190859, 0.20382982,
       0.24364472, 0.14515329, 0.12601022, 0.21755482, 0.12294954,
       0.18447018, 0.22224975, 0.1767815 , 0.19249867, 0.15795938])

In [52]:
mat_2

array([-0.29433235, -0.24128912, -0.15452273, -0.17853448, -0.08272959,
       -0.0137147 , -0.26708103,  0.1351999 ,  0.38250024, -0.11165838,
       -0.0237157 , -0.08558304,  0.29339706,  0.02458807,  0.02566362,
        0.32117796,  0.15814406,  0.22911953,  0.05851841, -0.17020329,
       -0.29099535, -0.0358394 ,  0.00531683, -0.0419998 ,  0.17877908,
        0.01559088,  0.20146626,  0.21325253,  0.1539758 ,  0.07719223])

In [53]:
ortho_mat=np.array([mat_1,mat_2]).T   # Finding the orthogonal matrix named as ortho_mat.
ortho_mat

array([[ 0.22227171, -0.29433235],
       [ 0.25098076, -0.24128912],
       [ 0.1661907 , -0.15452273],
       [ 0.18227975, -0.17853448],
       [ 0.19411459, -0.08272959],
       [ 0.22577866, -0.0137147 ],
       [ 0.2229515 , -0.26708103],
       [ 0.22772831,  0.1351999 ],
       [ 0.20822098,  0.38250024],
       [ 0.11007668, -0.11165838],
       [ 0.13432607, -0.0237157 ],
       [ 0.16524449, -0.08558304],
       [ 0.11755165,  0.29339706],
       [ 0.17776549,  0.02458807],
       [ 0.19348456,  0.02566362],
       [ 0.22626808,  0.32117796],
       [ 0.08788893,  0.15814406],
       [ 0.06652221,  0.22911953],
       [ 0.11190859,  0.05851841],
       [ 0.20382982, -0.17020329],
       [ 0.24364472, -0.29099535],
       [ 0.14515329, -0.0358394 ],
       [ 0.12601022,  0.00531683],
       [ 0.21755482, -0.0419998 ],
       [ 0.12294954,  0.17877908],
       [ 0.18447018,  0.01559088],
       [ 0.22224975,  0.20146626],
       [ 0.1767815 ,  0.21325253],
       [ 0.19249867,

In [54]:
daig_mat= np.round(ortho_mat.T@Array_matrix@eig_vect,decimals=8) # Finding the diagonal matrix named daig_mat 
daig_mat

array([[492.08633531,  -0.        ,  -0.        ,  -0.        ],
       [ -0.        ,  84.28858501,   0.        ,   0.        ]])

In [55]:
svd=ortho_mat@daig_mat@eig_vect.T   # here we are finding the svd values multiplying them and taking transpose .
svd

array([[  9.55125703,  18.64588151,  10.65345941, 109.66488982],
       [ 13.26935392,  27.63856586,  11.9168326 , 120.7681328 ],
       [  8.92975596,  18.68094755,   7.88441549,  79.79193039],
       [  9.54727349,  19.83491191,   8.65891017,  87.82097158],
       [ 13.0973115 ,  28.88835476,   9.08824693,  89.91239848],
       [ 17.48491538,  39.56675213,  10.46865534, 101.80510713],
       [ 10.34854257,  20.73848522,  10.65121607, 109.05387758],
       [ 21.70205892,  50.68469498,  10.37468871,  97.67396064],
       [ 26.90627076,  65.06221921,   9.16572945,  80.60395758],
       [  5.66062778,  11.70016819,   5.23377242,  53.16330021],
       [  9.97814808,  22.41523641,   6.24752687,  61.09149659],
       [ 10.73583275,  23.49585909,   7.75532945,  77.0495623 ],
       [ 17.30326717,  42.33168891,   5.07871526,  42.90121661],
       [ 14.73210861,  33.7113553 ,   8.1986579 ,  78.96601541],
       [ 16.00483302,  36.61286989,   8.92499086,  85.98559311],
       [ 26.66070453,  63

And Here the final answer . 

#                            Thank You .